fnb/urls.py
from django.urls import path
from fnb.views import (
    show_fnb
    )
from fnb.views import register, login_user, logout_user, add_fnb, search_fnbs, add_fnb_ajax, show_json, edit_fnb, delete_fnb, create_fnb_flutter, delete_fnb_flutter, update_fnb_flutter


app_name = 'fnb'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_fnb/', add_fnb, name='add_fnb'),
    path('search_fnbs/', search_fnbs, name='search_fnbs'),
    path('add_fnb_ajax/', add_fnb_ajax, name='add_fnb_ajax'),
    path('json/', show_json, name='show_json'),
    # path('get_fnb_data/<int:fnb_id>/', get_fnb_data, name='get_fnb_data'),
    # path('edit_fnb_ajax/<int:fnb_id>/', edit_fnb_ajax, name='edit_fnb_ajax'),
    path('fnb/edit_fnb/<uuid:id>/', edit_fnb, name='edit_fnb'),
    path('fnb/delete_fnb/<uuid:id>/', delete_fnb, name='delete_fnb'),
    # path('', landing_page, name='landing_page'),
    path('show_fnb', show_fnb, name='show_fnb'),
    path('create_flutter/', create_fnb_flutter, name='create_fnb_flutter'),
    path('delete_flutter/<uuid:id>/', delete_fnb_flutter, name='delete_fnb_flutter'),
    path('update_flutter/<uuid:id>/', update_fnb_flutter, name='update_fnb_flutter'),
]

location/urls.py
from django.urls import path
from location.views import show_location, location_details, location_search_ajax, show_json, show_json_by_id
from location.views import update_trivia


app_name = 'location'

urlpatterns = [
    path('', show_location, name='show_location'),
    path('search-location/', location_search_ajax, name='location_search_ajax'),
    path('location-details/', location_details, name='location_details'),
    path('update_trivia/', update_trivia, name='update_trivia'),
    path('json/', show_json, name= "json"),
    path('json/<str:id>', show_json_by_id, name="json_restaurant")
]

mineat/urls.py
from django.contrib import admin
from django.urls import path,include
from fnb import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("filter/",include("ingredient.urls")),
    path("fnb/",include("fnb.urls")),
    path("location/",include("location.urls")),
    path("restaurant/",include("restaurant.urls")),
    path("forum/",include("forum.urls")),
    path("review/",include("review.urls")),
    path('', views.landing_page, name='landing_page'),
    path('flutter/',include('database_commands.urls'))
]

restaurant/urls.py
from django.urls import path
from restaurant.views import show_restaurant, ajax_search_restaurant, ajax_search_district, ajax_search_fnb
from restaurant.views import restaurant_details, add_restaurant, delete_restaurant, edit_restaurant
from restaurant.views import add_restaurant_ajax, show_json, show_json_by_id


app_name = 'restaurant'

urlpatterns = [
    path('', show_restaurant, name='show_restaurant'),
    path('search-restaurant/', ajax_search_restaurant, name='ajax_search_restaurant'),
    path('search-district/', ajax_search_district, name='ajax_search_district'),
    path('search-fnb/', ajax_search_fnb, name='ajax_search_fnb'),
    path('restaurant-details/', restaurant_details, name='restaurant_details'),
    path('add-restaurant/', add_restaurant, name='add_restaurant'),
    path('delete/<uuid:id>', delete_restaurant, name='delete_restaurant'),
    path('edit-restaurant/<uuid:id>', edit_restaurant, name='edit_restaurant'),
    path('add-restaurant-ajax/', add_restaurant_ajax, name='add_restaurant_ajax'),
    path('json/', show_json, name="json"),
    path('json/<str:id>', show_json_by_id, name="json_restaurant")
]

review/urls.py
from django.urls import path
from review.views import show_review, add_review, like_review, load_reviews, load_write_review, delete_review, edit_review,show_json, create_review_flutter

app_name = 'review'

urlpatterns = [
    path('', show_review, name='show_review'),
    path('add-review/', add_review, name='add_review'),
    path('like-review/', like_review, name='like_review'),
    path('load_reviews/', load_reviews, name='load_reviews'),
    path('load_write_review/', load_write_review, name='load_write_review'),
    path('delete/<uuid:id>', delete_review, name='delete_review'),
    path('edit-review/<uuid:id>', edit_review, name='edit_review'),
    path("<uuid:id>/json/", show_json, name= "json"),
    path('create-flutter/', create_review_flutter, name='create_review_flutter'),
    
]

restaurant/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from location.models import Location
from fnb.models import Fnb

# Create your models here.
class Restaurant(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=127)
    address = models.TextField()
    location = models.ForeignKey(Location,on_delete=models.CASCADE)
    fnb = models.ManyToManyField(Fnb,related_name= "restaurant_fnb")
    image = models.CharField(max_length=511)

restaurant/forms.py
from django import forms
from .models import Restaurant, Location, Fnb

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['name', 'image', 'address', 'location', 'fnb']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # For location, show the name instead of object representation
        self.fields['location'].queryset = Location.objects.all()
        self.fields['location'].label_from_instance = lambda obj: obj.name

        # For fnb, show the names instead of object representation
        self.fields['fnb'].required = False
        self.fields['fnb'].widget = forms.CheckboxSelectMultiple()
        self.fields['fnb'].queryset = Fnb.objects.all()
        self.fields['fnb'].label_from_instance = lambda obj: obj.name

restaurant/views.py
from django.http import JsonResponse
from ingredient.models import Ingredient
from django.template.loader import render_to_string
from django.shortcuts import render, redirect
from restaurant.models import Restaurant
from django.core import serializers
from location.models import Location
from restaurant.forms import RestaurantForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def show_restaurant(request):
    restaurants = Restaurant.objects.all()
    context = {
        "restaurants": restaurants
    }
    return render(request, "show_restaurant.html", context)

def ajax_search_restaurant(request):
    query = request.GET.get('q', '')
    if query:
        restaurants = Restaurant.objects.filter(name__icontains=query)
    else:
        restaurants = Restaurant.objects.all()

    html = render_to_string('hasil_search_restaurant.html', {'restaurants': restaurants})
    return JsonResponse({'html': html})

def ajax_search_district(request):
    location_query = request.GET.get('location_q', '')

    if location_query:
        restaurants = Restaurant.objects.filter(location__name__icontains=location_query)
    else:
        restaurants = Restaurant.objects.all()

    html = render_to_string('hasil_search_restaurant.html', {'restaurants': restaurants})
    return JsonResponse({'html': html})

def ajax_search_fnb(request):
    fnb_query = request.GET.get('fnb_q', '')

    if fnb_query:
        restaurants = Restaurant.objects.filter(fnb__name__icontains=fnb_query).distinct()
    else:
        restaurants = Restaurant.objects.all()

    html = render_to_string('hasil_search_restaurant.html', {'restaurants': restaurants})
    return JsonResponse({'html': html})

def restaurant_details(request):
    restaurant_id = request.GET.get('id')
    restaurant = Restaurant.objects.get(id=restaurant_id)
    context = {
        "restaurant": restaurant,
        "fnb_items": restaurant.fnb.all(),
    }
    return render(request, "restaurant_details.html", context)

def add_restaurant(request):
    form = RestaurantForm(request.POST or None)
    if form.is_valid() and request.method == "POST":
        restaurant = form.save(commit=False)
        restaurant.save()
        form.save_m2m()
        return redirect('restaurant:show_restaurant')

    context = {'form': form}
    return render(request, "add_restaurant.html", context)

def delete_restaurant(request, id):
    restaurant = Restaurant.objects.get(pk=id)
    restaurant.delete()
    return HttpResponseRedirect(reverse('restaurant:show_restaurant'))

def edit_restaurant(request, id):
    order = Restaurant.objects.get(pk = id)

    form = RestaurantForm(request.POST or None, instance=order)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('restaurant:show_restaurant'))

    context = {'form': form}
    return render(request, "edit_restaurant.html", context)  

def add_restaurant_ajax(request):
    if request.method == "POST":
        form = RestaurantForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            html = render_to_string('add_restaurant_ajax.html', {'form': form}, request=request)
            return JsonResponse({'success': False, 'html': html})
    else:
        form = RestaurantForm()
        html = render_to_string('add_restaurant_ajax.html', {'form': form}, request=request)
        return JsonResponse({'html': html})
    

def show_json(request):
    data = []
    for i in Restaurant.objects.all():
        foods = []
        for j in i.fnb.all():
            

            ingredients_list = ""

            for ingredient in Ingredient.objects.filter(fnb=j):
                    ingredients_list += f"{ingredient.name}, "
            foods.append(
                {
                    "id" : j.id,
                    "title": j.name,
                    "price": j.price,
                    "description": j.description,
                    "ingredients": ingredients_list,
                    "imageUrl": j.image.url
                }
            )
        data.append({
            "title": i.name,
            "address" : i.address,
            "district" : i.location.name,
            "imageUrl": i.image,
            "foodsInTheRestaurant": foods,
        })
    return JsonResponse(data,safe=False)

def show_json_by_id(request, id):
    data = []
    for i in Restaurant.objects.filter(name=id):
        foods = []
        for j in i.fnb.all():
            

            ingredients_list = ""

            for ingredient in Ingredient.objects.filter(fnb=j):
                    ingredients_list += f"{ingredient.name}, "
            foods.append(
                {
                    "id" : j.id,
                    "title": j.name,
                    "price": j.price,
                    "description": j.description,
                    "ingredients": ingredients_list,
                    "imageUrl": j.image.url
                }
            )
        data.append({
            "title": i.name,
            "address" : i.address,
            "district" : i.location.name,
            "imageUrl": i.image,
            "foodsInTheRestaurant": foods,
        })
    return JsonResponse(data,safe=False)

restaurant/templates/add_restaurant.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Add Restaurant</title>
{% endblock meta %}

{% block content %}
{% include 'show_header.html' %}
<div class="flex justify-start mb-4 pt-20 pl-20">
  <a href="{% url 'restaurant:show_restaurant' %}" class="text-red-500 hover:text-lime-500 font-semibold">
      &larr; Back to All Restaurants
  </a>
</div>
<div class="flex flex-col min-h-screen bg-yellow-500">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-white">Add Restaurant</h1>

    <div class="bg-red-900 shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-white">
              {{ field.label }}
            </label>
            <div class="w-full">
              {% if field.name == 'fnb' %}
                <div class="flex flex-col space-y-2">
                  {% for checkbox in field %}
                    <label class="inline-flex items-center">
                      {{ checkbox.tag }}
                      <span class="ml-2">{{ checkbox.choice_label }}</span>
                    </label>
                  {% endfor %}
                </div>
              {% else %}
                {{ field }}
              {% endif %}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-sky-500 hover:bg-lime-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 transition duration-300 ease-in-out w-full">
            Add Restaurant
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

restaurant/templates/add_restaurant_ajax.html
<div class="bg-red-900 shadow-md rounded-lg p-6 form-style">
    <h2 class="text-2xl font-bold text-center mb-6 text-white">Add Restaurant</h2>
    <form id="ajax-add-restaurant-form" method="post" class="space-y-6">
      {% csrf_token %}
      {% for field in form %}
        <div class="flex flex-col">
          <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-white">
            {{ field.label }}
          </label>
          <div class="w-full">
            {% if field.name == 'fnb' %}
              <div class="flex flex-col space-y-2">
                {% for checkbox in field %}
                  <label class="inline-flex items-center">
                    {{ checkbox.tag }}
                    <span class="ml-2">{{ checkbox.choice_label }}</span>
                  </label>
                {% endfor %}
              </div>
            {% else %}
              {{ field }}
            {% endif %}
          </div>
          {% if field.help_text %}
            <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
          {% endif %}
          {% for error in field.errors %}
            <p class="mt-1 text-sm text-red-600">{{ error }}</p>
          {% endfor %}
        </div>
      {% endfor %}
      <div class="flex justify-center mt-6">
        <button type="submit" class="bg-sky-500 hover:bg-lime-500 text-white font-semibold px-6 py-3 rounded-lg transition duration-300 ease-in-out w-full">
          Add Restaurant
        </button>
      </div>
    </form>
  </div>  

restaurant/templates/edit_restaurant.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Restaurant</title>
{% endblock meta %}

{% block content %}
<body class="bg-gray-700"></body>
<div class="flex flex-col min-h-screen">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-white">Edit Restaurant</h1>

    <div class="bg-white shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {% if field.name == 'fnb' %}
                <div class="flex flex-col space-y-2">
                  {% for checkbox in field %}
                    <label class="inline-flex items-center">
                      {{ checkbox.tag }}
                      <span class="ml-2">{{ checkbox.choice_label }}</span>
                    </label>
                  {% endfor %}
                </div>
              {% else %}
                {{ field }}
              {% endif %}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-sky-500 hover:bg-lime-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 transition duration-300 ease-in-out w-full">
            Edit Restaurant
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

restaurant/templates/hasil_search_restaurant.html
{% for restaurant in restaurants %}
    <a href="{% url 'restaurant:restaurant_details' %}?id={{ restaurant.id }}" 
    class="restaurant-item bg-red-900 shadow-md rounded-lg overflow-hidden transform transition duration-300 hover:scale-105">
            <div class="p-4">
                <h2 class="text-white text-3xl font-bold">{{ restaurant.name }}</h2><br>
                <p class="text-white">{{ restaurant.address }}</p><br><br>
                <img src="{{ restaurant.image }}" alt="{{ restaurant.name }}" class="w-full h-32 object-cover rounded-md">
            </div>
        </a>
    {% endfor %}

restaurant/templates/restaurant_details.html
{% extends "base.html" %}

{% block meta %}
    <title>{{ restaurant.name }} - Restaurant Details</title>
{% endblock meta %}

{% block content %}
{% include 'show_header.html' %}

<div class="bg-white max-w-7xl mx-auto p-4 pt-20 ">

    <!-- Back Button -->
    <div class="flex justify-start mb-4">
        <a href="{% url 'restaurant:show_restaurant' %}" class="text-red-500 hover:underline font-semibold">
            &larr; Back to All Restaurants
        </a>
    </div>

    <!-- Restaurant Name and Image -->
    <div class="bg-red-900 shadow-md rounded-lg p-6 mb-4">
        <div class="flex justify-between items-center">
            <h1 class="text-white text-4xl font-bold">{{ restaurant.name }}</h1>
            {% if user.is_authenticated and user.is_staff %}
            <div class="flex flex-col items-end">
                <a href="{% url 'restaurant:delete_restaurant' restaurant.pk %}" class="text-red-500 hover:text-red-700 font-semibold mb-1">
                    Delete Restaurant
                </a>
                <a href="{% url 'restaurant:edit_restaurant' restaurant.pk %}" class="text-yellow-500 hover:text-red-700 font-semibold">
                    Edit Restaurant
                </a>
            </div>
            {% endif %}
        </div>
        <br>
        <img src="{{ restaurant.image }}" alt="{{ restaurant.name }}">
    </div>

    <!-- Restaurant Address and District Link -->
    <div class="bg-red-900 shadow-md rounded-lg p-6 mb-4">
        <h2 class="text-white text-2xl font-semibold">Address:</h2>
        <p class="text-white">{{ restaurant.address }}</p>
        <br>
        <h2 class="text-white text-2xl font-semibold">District:</h2>
        <p class="text-white">{{ restaurant.location.name }}</p>
        <a href="{% url 'location:location_details' %}?id={{ restaurant.location.id }}" class="text-yellow-500 hover:underline">
            Want to know more about the district?
        </a>
    </div>

    <!-- Restaurant Menu -->
    <div class="bg-red-900 shadow-md rounded-lg p-6 mb-4">
        <h2 class="text-white text-2xl font-semibold">Menu</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">
            {% for fnb_item in restaurant.fnb.all %}
                <div class="bg-white shadow-md rounded-lg p-4">
                    <a href="{% url 'review:show_review' %}?id={{ fnb_item.id }}">
                        <img src="{{ fnb_item.image }}" alt="{{ fnb_item.name }}" class="w-full h-48 object-cover rounded-md transform transition duration-300 hover:scale-105">
                    </a>
                    <h3 class="text-xl font-semibold mt-2">{{ fnb_item.name }}</h3>
                    <p class="text-gray-600 mt-1">{{ fnb_item.description }}</p>
                    <p class="text-indigo-600 font-bold mt-2">Rp {{ fnb_item.price }}</p>
                </div>
            {% empty %}
                <p class="col-span-full text-white">What restaurant doesn't sell any food? This one</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

restaurant/templates/show_restaurant.html
{% extends "base.html" %}

{% block meta %}
    <title>Restaurants</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock meta %}

{% block content %}
{% include 'show_header.html' %}
<!-- Search Bar -->
<nav class="bg-white shadow-md pt-20 p-4 sticky top-0 z-20">
    <div class="max-w-7xl mx-auto flex items-center justify-between">
        <div class="flex space-x-2 w-full">
            <!-- Search Options -->
            <select id="search-choice" class="font-spartan border rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-yellow-500">
                <option value="name">Search by Name</option>
                <option value="district">Search by District</option>
                <option value="fnb">Search by Menu</option>
            </select>

            <!-- Search input -->
            <input 
                type="text" 
                id="search-input" 
                placeholder="Search..." 
                autocomplete="off" 
                class="flex-grow border rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-yellow-500"
            >
        </div>
    </div>
</nav>

<!-- Only Admin/Staff can see this button -->
{% if user.is_authenticated and user.is_staff %}
<div class="flex justify-center mt-6 mb-6 ">
    <button id="ajax-add-restaurant-btn" class="bg-yellow-500 hover:bg-lime-500 text-white font-serif font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 mx-4">
        Add Restaurant
    </button>
</div>
{% endif %}

<!-- Add Restaurant Form AJAX  -->
<div id="ajax-add-restaurant-modal" class="hidden fixed z-50 inset-0 flex items-center justify-center bg-gray-900 bg-opacity-50 overflow-y-auto">
    <div class="bg-yellow-500 p-6 rounded-lg shadow-lg w-full max-w-3xl max-h-screen overflow-y-auto">
        <button id="close-modal" class="float-right text-gray-700 hover:text-red-500 font-bold">&times;</button>
        <div id="ajax-add-restaurant-content" class="max-h-[80vh] overflow-y-auto p-4">
        </div>
    </div>
</div>

<!-- Search Results -->
<div id="search-results" class="font-spartan max-w-7xl mx-auto p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    {% for restaurant in restaurants %}
    <a href="{% url 'restaurant:restaurant_details' %}?id={{ restaurant.id }}" 
    class="restaurant-item bg-red-900 shadow-md rounded-lg overflow-hidden transform transition duration-300 hover:scale-105">
            <div class="p-4">
                <h2 class="text-white text-3xl font-bold">{{ restaurant.name }}</h2><br>
                <p class="text-white">{{ restaurant.address }}</p><br><br>
                <img src="{{ restaurant.image }}" alt="{{ restaurant.name }}" class="w-full h-32 object-cover rounded-md">
            </div>
        </a>
    {% endfor %}
</div>

<script>
    $(document).ready(function() {
        function search() {
            let query = $('#search-input').val();
            let choice = $('#search-choice').val();
            let url, dataKey;

            switch (choice) {
                case 'district':
                    url = "{% url 'restaurant:ajax_search_district' %}";
                    dataKey = 'location_q';
                    break;
                case 'fnb':
                    url = "{% url 'restaurant:ajax_search_fnb' %}";
                    dataKey = 'fnb_q';
                    break;
                default:
                    url = "{% url 'restaurant:ajax_search_restaurant' %}";
                    dataKey = 'q';
            }

            $.ajax({
                url: url,
                method: 'GET',
                data: { [dataKey]: query },
                success: function(response) {
                    $('#search-results').html(response.html);
                },
                error: function(xhr, status, error) {
                    console.error('Search error:', error);
                }
            });
        }

        $('#search-input').on('keyup', function() {
            search();
        });

        $('#search-choice').on('change', function() {
            search();
        });
    });
    $(document).ready(function() {
    $('#ajax-add-restaurant-btn').on('click', function() {
        $.ajax({
            url: "{% url 'restaurant:add_restaurant_ajax' %}",
            method: 'GET',
            success: function(response) {
                $('#ajax-add-restaurant-content').html(response.html);
                $('#ajax-add-restaurant-modal').removeClass('hidden');
                $('#ajax-add-restaurant-modal')[0].scrollTop = 0; // Scroll to the top of the modal
            }
        });
    });

    $('#close-modal').on('click', function() {
        $('#ajax-add-restaurant-modal').addClass('hidden');
    });

    $(document).on('submit', '#ajax-add-restaurant-form', function(e) {
        e.preventDefault();
        $.ajax({
            url: "{% url 'restaurant:add_restaurant_ajax' %}",
            method: 'POST',
            data: $(this).serialize(),
            success: function(response) {
                if (response.success) {
                    $('#ajax-add-restaurant-modal').addClass('hidden');
                    location.reload();
                } else {
                    $('#ajax-add-restaurant-content').html(response.html);
                }
            }
        });
    });
});
</script>
{% endblock content %}